In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/iris/database.sqlite
/kaggle/input/iris/Iris.csv


# Importing the Libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

# Reading in our Data


In [3]:
df = pd.read_csv("/kaggle/input/iris/Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

# Data Cleaning


In [5]:
df.drop(columns=['Id'],inplace=True)


In [6]:
df.head()


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

# Data Analysis

In [7]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
df.describe()


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [9]:
df['Species'].unique()


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [10]:
species_dummies = pd.get_dummies(df.Species)
df=pd.concat([df,species_dummies],axis=1)

In [11]:
df.drop(columns='Species',inplace=True)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
0            5.1           3.5            1.4           0.2            1   
1            4.9           3.0            1.4           0.2            1   
2            4.7           3.2            1.3           0.2            1   
3            4.6           3.1            1.5           0.2            1   
4            5.0           3.6            1.4           0.2            1   

   Iris-versicolor  Iris-virginica  
0                0               0  
1                0               0  
2                0               0  
3                0               0  
4                0               0

# Features and labels

In [12]:
X =df.iloc[:,:4]
y=df.iloc[:,4:]

In [13]:
X.head()


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [14]:
y.head()

Iris-setosa  Iris-versicolor  Iris-virginica
0            1                0               0
1            1                0               0
2            1                0               0
3            1                0               0
4            1                0               0

In [15]:
type(X)

pandas.core.frame.DataFrame

In [16]:
type(y)

pandas.core.frame.DataFrame

# Converting from pandas to Numpy 

In [17]:
X=X.values
y=y.values


In [18]:
type(X)

numpy.ndarray

In [19]:
type(y)

numpy.ndarray

# Spliting our data into training and testing

In [20]:
from sklearn.model_selection import train_test_split


In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

# Creating our FeedForward Neural Network.

In [22]:
import tensorflow as tf
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.models import Sequential

In [23]:
model = Sequential()
model.add(Dense(units=128,activation='relu',input_dim=4))
model.add(Dropout(0.2))
model.add(Dense(units=100,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=3,activation='softmax'))

In [24]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [25]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120, 3)


In [26]:
model.fit(X_train,y_train,epochs=200)


Train on 120 samples
Epoch 1/200
120/120 [==============================] - 1s 7ms/sample - loss: 0.2524 - accuracy: 0.4083
Epoch 2/200
120/120 [==============================] - 0s 124us/sample - loss: 0.2080 - accuracy: 0.5083
Epoch 3/200
120/120 [==============================] - 0s 123us/sample - loss: 0.1840 - accuracy: 0.5583
Epoch 4/200
120/120 [==============================] - 0s 116us/sample - loss: 0.1801 - accuracy: 0.5667
Epoch 5/200
120/120 [==============================] - 0s 116us/sample - loss: 0.1603 - accuracy: 0.6333
Epoch 6/200
120/120 [==============================] - 0s 112us/sample - loss: 0.1381 - accuracy: 0.6750
Epoch 7/200
120/120 [==============================] - 0s 122us/sample - loss: 0.1446 - accuracy: 0.6500
Epoch 8/200
120/120 [==============================] - 0s 124us/sample - loss: 0.1292 - accuracy: 0.6750
Epoch 9/200
120/120 [==============================] - 0s 120us/sample - loss: 0.1206 - accuracy: 0.7083
Epoch 10/200
120/120 [==============

# Evaluating our Results

In [27]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)

In [28]:
y_pred


array([[2.7613321e-03, 9.7445041e-01, 2.2788217e-02],
       [3.1346521e-05, 6.6178508e-02, 9.3379009e-01],
       [1.4462915e-05, 1.2649547e-02, 9.8733598e-01],
       [4.8964527e-03, 9.9123585e-01, 3.8676197e-03],
       [9.9902582e-01, 9.7422209e-04, 3.2840208e-10],
       [3.8968796e-05, 2.5410660e-02, 9.7455037e-01],
       [4.1589551e-03, 9.9194932e-01, 3.8917062e-03],
       [9.9887508e-01, 1.1249112e-03, 3.6885503e-10],
       [9.9969602e-01, 3.0404638e-04, 1.5081767e-11],
       [9.9628037e-01, 3.7196230e-03, 7.0408475e-09],
       [4.4545261e-03, 9.4136226e-01, 5.4183256e-02],
       [2.0022426e-06, 7.8673586e-03, 9.9213058e-01],
       [9.9859470e-01, 1.4053134e-03, 6.0931621e-10],
       [9.9624050e-01, 3.7595013e-03, 7.0263320e-09],
       [3.6747992e-06, 1.3133633e-02, 9.8686266e-01],
       [5.9752068e-03, 9.6917379e-01, 2.4851039e-02],
       [9.8930756e-03, 9.8741817e-01, 2.6887499e-03],
       [9.9786830e-01, 2.1316307e-03, 3.1169880e-09],
       [2.5870408e-05, 1.926

In [29]:
y_pred.round()


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [30]:
y_test

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0]], dtype=uint8)

In [31]:
y_pred = (y_pred > 0.5) 
y_pred

array([[False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False]])

In [32]:
a=np.argmax(y_pred,axis=1)

In [33]:
a

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 2, 0, 0, 2,
       2, 0, 0, 1, 1, 2, 2, 0])

In [34]:
b=np.argmax(y_test,axis=1)


In [35]:
b

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 2, 0, 0, 2,
       2, 0, 0, 1, 1, 2, 2, 0])

In [36]:
cm = confusion_matrix(a,b)


In [37]:
cm

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 10]])

In [38]:
df.tail()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
145            6.7           3.0            5.2           2.3            0   
146            6.3           2.5            5.0           1.9            0   
147            6.5           3.0            5.2           2.0            0   
148            6.2           3.4            5.4           2.3            0   
149            5.9           3.0            5.1           1.8            0   

     Iris-versicolor  Iris-virginica  
145                0               1  
146                0               1  
147                0               1  
148                0               1  
149                0               1

In [39]:
model.predict([[5.9,3.0,5.1,1.8]]).round()


array([[0., 0., 1.]], dtype=float32)

In [40]:
model.save("iris.h5")
